title: "Geolimpiade Wiki"
description: "Materi Olimpiade Geografi"
baseurl: "/Geolimpiade-Wiki"
url: "https://andiaya.github.io"

remote_theme: "mmistakes/minimal-mistakes"

# Minimal Mistakes settings
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

search: true
search_full_content: true

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name: "Ryan Andri Wijaya"
  bio: "My bio"

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "docs"
